version: '3'

services:
    web:
        image: nginx:latest
        links:
            - db
            - php
        volumes:
            - ./:/var/www/html
            - .docker/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8081:80
            - 8181:80
            - 8281:80
        working_dir: /var/www/html

    php:
        build:
            context: ./
            dockerfile: .docker/Dockerfile-php-fpm
        links:
            - db
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            DB_HOST: db

    db:
        image: mysql:8.0.3
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: mydatabase
        ports:
            - 3306:3306
